stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: .
  TF_VERSION: "1.5.7"

cache:
  paths:
    - .terraform

before_script:
  - rm -rf .terraform
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin/
  - terraform --version

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate

plan:
  stage: plan
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
  only:
    - main

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  only:
    - main
  when: manua
