name: Yandex Cloud Terraform CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  TF_VERSION: "1.5.7"
  YC_FOLDER_ID: "b1gsg9mk694pae2d18og"
  YC_CLOUD_ID: "b1grurkigc4agd16neb0"
  TF_BACKEND_BUCKET: "storage-website-test"
  YC_STORAGE_ENDPOINT: "https://storage.yandexcloud.net"
  YC_REGION: "ru-central1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}


      - name: Terraform Init
        working-directory: ./terraform/kub
        run: |
          terraform init -reconfigure \
            -backend-config="access_key=${{ secrets.YC_STORAGE_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.YC_STORAGE_SECRET_KEY }}" \
            -backend-config="endpoint=https://storage.yandexcloud.net" \
            -backend-config="bucket="storage-website-test" \
            -backend-config="region=ru-central1" \
            -backend-config="skip_region_validation=true" \
            -backend-config="force_path_style=true"

      - name: Terraform Plan
        working-directory: ./terraform/kub
        run: terraform plan -out=tfplan
        if: github.ref == 'refs/heads/main'

      - name: Terraform Apply
        working-directory: ./terraform/kub
        run: terraform apply -auto-approve tfplan
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
