name: Terraform Plan and Apply

on:
  push:
    branches: [ "main" ]  # Запуск при пуше в ветку main
  pull_request:           # Запуск при создании/изменении PR
    branches: [ "main" ]

env:
  TF_VERSION: "1.5.7"

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        if: github.ref == 'refs/heads/main'

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        if: github.ref == 'refs/heads/main'
